config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  devise_for :users, :controllers => { :registrations => :registrations }

  root to: 'pages#home'

  resources :rooms do
    member do
      get 'bookings', to: 'rooms#bookings'
    end

    resources :room_images, only: [:destroy]
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :show, :destroy, :update]

  get '/users/:id/profile', to: 'users#show', as: 'profile'

  get '/my_rooms', to: 'rooms#myrooms', as: 'my_rooms'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :status, presence: true, allow_blank: false
  validates :user_id, presence: true, allow_blank: false
  validates :room_id, presence: true, allow_blank: false
  belongs_to :user
  belongs_to :room

  def cost
    ((self.end_time - self.start_time) / 3600).floor * self.room.price
  end

  def color
    if self.status == 'pending'
      '#ff8f56'
    elsif self.status == 'accepted'
      '#20716a'
    else
      '#ff5959'
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  validates :instrument_type, presence: true
  validates :description, presence: true, allow_blank: false
  validates :location, presence: true, allow_blank: false, inclusion: { in: ['Shanghai', 'Seoul', 'Chengdu', 'Beijing', 'Hong Kong', 'Barcelona'], message: "We aren't in that city yet!" }
  validates :price, presence: true, allow_blank: false
  validates :user_id, presence: true, allow_blank: false
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :room_images, dependent: :destroy
  accepts_nested_attributes_for :room_images
  has_many :bookings, dependent: :destroy
  belongs_to :user

  def currency
    if ['Shanghai', 'Chengdu', 'Beijing'].include?(self.location)
      '¥'
    elsif self.location == 'Hong Kong'
      'HK$'
    elsif self.location == 'Seoul'
      '₩'
    else
      '€'
    end
  end
end

app/models/room_image.rb
class RoomImage < ApplicationRecord
  mount_uploader :image, PhotoUploader

  validates :image, presence: true
  validates :room_id, presence: true, allow_blank: false
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :avatar, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :city, :avatar])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :destroy, :update]
  def index
    @all_bookings = Booking.all
    @myrooms = Room.where(user_id: current_user.id)
    @my_hostings = []
    @myrooms.each do |room|
      room.bookings.each do |booking|
        @my_hostings << booking
      end
    end
    @my_bookings = Booking.where(user_id: current_user.id)
  end

  def show
  end

  def new
    @booking = Booking.new
    @room = Room.find(params[:room_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @room = Room.find(params[:room_id])
    @booking.user = current_user
    @booking.room = @room
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  def update
    @booking.status = params[:status]
    @booking.save
    redirect_to bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # subject to change...
  # should we include other pages like search results, show pages
  skip_before_action :authenticate_user!, only: :home
  def home
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_update_path_for(resource)
    profile_path(current_user)
  end
end

app/controllers/room_images_controller.rb
class RoomImagesController < ApplicationController

  def destroy
    image = RoomImage.find(params[:id])
    image.destroy
    redirect_to room_path(Room.find(params[:room_id]))
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_room, only: [:show, :edit, :update, :destroy, :bookings]

  def index
    if params[:room].nil?
      @rooms = Room.all
    elsif params[:room][:instrument_type] == "" && params[:room][:location] == ""
      @rooms = Room.all
    elsif params[:room][:instrument_type] != "" && params[:room][:location] != ""
      sql_query = "instrument_type ILIKE :instrument_type AND location ILIKE :location"
      @rooms = Room.where(sql_query, instrument_type: "#{params[:room][:instrument_type]}", location: "#{params[:room][:location]}")
    elsif params[:room][:instrument_type] != ""
      sql_query = "instrument_type ILIKE :instrument_type"
      @rooms = Room.where(sql_query, instrument_type: "#{params[:room][:instrument_type]}")
    elsif params[:room][:location] != ""
      sql_query = "location ILIKE :location"
      @rooms = Room.where(sql_query, location: "#{params[:room][:location]}")
    end
    unless @rooms.nil?
      @map_rooms = @rooms.where.not(latitude: nil).where.not(longitude: nil)
      @markers = @map_rooms.map do |room|
        {
          lng: room.longitude,
          lat: room.latitude,
          infoWindow: { content: render_to_string(partial: "/rooms/map_window", locals: { room: room }) }
        }
      end
    end
  end

  def show
    @markers = [{
      lng: @room.longitude,
      lat: @room.latitude,
      infoWindow: { content: render_to_string(partial: "/rooms/map_window", locals: { room: @room }) }
    }]
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user = current_user
    if @room.save
      if params[:room][:image]
        params[:room][:image].each do |i|
          @room.room_images.create(image: i)
        end
      end
      redirect_to room_path(@room), notice: 'Room successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @room.update(room_params)
    if @room.save
      if params[:room][:image]
        params[:room][:image].each do |i|
          @room.room_images.create(image: i)
        end
      end
      redirect_to room_path(@room), notice: 'Room successfully updated.'
    else
      render :new
    end
  end

  def destroy
    @room.destroy
  end

  def myrooms
    @myrooms = Room.where(user_id: current_user.id)
  end

  def bookings
    @bookings = Booking.where(@room)
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:instrument_type, :description, :location, :price, :address, :currency, room_images_attributes: [:id, :room_id, :image])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for([@room, @booking]) do |f| %>
  <div class="row"> <div class="col-xs-6">
    <%= f.input :start_time, placeholder: "Start time", as: :string, required: false, label: false, input_html: {class: "datepicker"} %>
  </div> <div class="col-xs-6">
    <%= f.input :end_time, placeholder: "End time", as: :string, required: false, label: false, input_html: {class: "datepicker"} %>
   </div></div>
  <%= f.button :submit, 'Send a booking request now!', class: "btn-signup" %>
<% end %>

app/views/bookings/index.html.erb
<div class="profile" style="background-image: linear-gradient(145deg, rgba(109, 95, 208, 0.5), rgba(45, 225, 207, 0.5))">
 <div style="background-image:  linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.2)), url('<%=image_path 'bg.png' %>');">
<div class="container dashboard mybookings" id="booking-background">
  <div class="dashboard-main-header">
    <h1>Dashboard</h1>
  </div>
  <div class="dashboard-subheading">
    <h3 class="mybookings-subheading">Rehearsals I will host:</h3>

    <% if @my_hostings.count > 0 %>

    <div class="row">
      <% @my_hostings.each do |booking| %>
        <div class="col-xs-6 col-sm-4">

          <div class="card card-mybooking">
            <% if booking.room.room_images.count > 0 %>
             <%= link_to booking_path(booking) do %>
              <div class="picture" style="background-image:  url(<%= cl_image_path(booking.room.room_images[0].image) %>);">

              </div>
              <% end %>
            <% else %>
              <%= link_to booking_path(booking) do %>
              <div class="picture" style="background-image: url('https://images.unsplash.com/photo-1526142684086-7ebd69df27a5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f5767f515cad13d5aa42559ec8bb9a55&auto=format&fit=crop&w=1950&q=80');">
              </div>
              <% end %>

            <% end %>


            <div class="card-description">
              <% if booking.user.first_name %>
              <h3><%= booking.user.first_name %>'s request</h3>
              <% else %>
              <h3><%= booking.user.email.split('@')[0].capitalize %>'s request</h3>
              <% end %>

              <p>Location: <%= booking.room.location %></p>
              <p>Rental price:
              <% if ['Shanghai', 'Chengdu', 'Beijing'].include?(booking.room.location) %>
                  ¥
              <% elsif booking.room.location == 'Hong Kong' %>
                  HK$
              <% elsif booking.room.location == 'Seoul' %>
                  ₩
              <% else %>
                  €
              <% end %>
                <%= booking.room.price %>/hr</p>
            </div>


            <div class="card-links">

              <% if booking.status == 'pending' %>

                <%= link_to 'Accept', booking_path(booking, status: 'accepted'), method: :patch, class: "btn btn-primary btn-mybooking accept" %>
                <%= link_to 'Decline', booking_path(booking, status: 'declined'), method: :patch, class: "btn btn-primary btn-mybooking decline" %>

                <% elsif booking.status == 'accepted' %>
                <p><i class="fas fa-check"></i> You accepted <%= booking.user.first_name %>'s booking</p>
                <% else %>
                <p><i class="fas fa-times"> </i> You declined <%= booking.user.first_name %>'s booking</p>
                <% end %>
            </div>

          </div>
        </div>
      <% end %>
    </div>
    <% else %>
    <h4 class="booking-status">🥺 You don't have any rehearsals to host at the moment.</h4>
    <% end %>
  </div>

  <div class="dashboard-subheading">
    <h3 class="mybookings-subheading">Rehearsals I have booked:</h3>
    <% if @my_bookings.count > 0 %>
    <div class="row">
      <% @my_bookings.each do |booking| %>
        <div class="col-xs-6 col-sm-4">
          <div class="card card-mybooking">
            <% if booking.room.room_images.count > 0 %>
              <%= link_to booking_path(booking) do %>
              <div class="picture" style="background-image: url(<%= cl_image_path(booking.room.room_images[0].image) %>);">
              </div>
              <% end %>
            <% else %>
              <%= link_to booking_path(booking) do %>
              <div class="picture" style="background-image: url('https://images.unsplash.com/photo-1526142684086-7ebd69df27a5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f5767f515cad13d5aa42559ec8bb9a55&auto=format&fit=crop&w=1950&q=80');">
              </div>
              <% end %>

            <% end %>

            <div class="card-description booking-description">
              <% if booking.status == 'pending' %>
                <i class="fas fa-spinner"></i> <%= booking.status.capitalize %>
                <% elsif booking.status == 'accepted' %>
                <i class="fas fa-check"></i> <%= booking.status.capitalize %>
                <% else %>
                <i class="fas fa-times"></i> <%= booking.status.capitalize %>
              <% end %>

              <h3><%= booking.room.instrument_type %> in <%= booking.room.location %></h3>
              <p>Host: <%= User.find(booking.room.user_id).first_name %></p>
              <p>Location: <%= booking.room.location %></p>
              <p>Rental price:
              <% if booking.room.currency == 'Chinese Yuan' %>
                  ¥
              <% elsif booking.room.currency == 'HK Dollar' %>
                  HK$
              <% elsif booking.room.currency == 'Won' %>
                  ₩
              <% else %>
                  €
              <% end %>
                <%= booking.room.price %>/hr</p>
            </div>


          </div>
        </div>
      <% end %>
    </div>
    <% else %>
    <h4 class="booking-status">😳 You don't have any upcoming rehearsals to go.</h4>
    <% end %>
  </div>
</div>
</div>
</div>

app/views/bookings/new.html.erb
<div class="banner-login" style="background-image: linear-gradient(336deg, rgba(32,70,245,.8), rgba(32,70,245,0) 70.71%), url('https://images.unsplash.com/photo-1519683109079-d5f539e1542f?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=444379486abceadfb5dd5ad3df46c58a&auto=format&fit=crop&w=1950&q=80');">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="card-book">
      <h1 class="log-title">When would you like the space?</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
  <% if @booking.room.room_images.count > 0 %>
    <div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path(@booking.room.room_images[0].image) %>);">
    </div>
  <% else %>
    <div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1526142684086-7ebd69df27a5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f5767f515cad13d5aa42559ec8bb9a55&auto=format&fit=crop&w=1950&q=80');">
    </div>
  <% end %>


  <div class="container show-container">
    <div class="show-box">
      <div class="title-box">
        <h3>Rehearsal at <%= @booking.room.user.first_name %>'s house</h3>
      </div>
      <div class="image-box">
        <div class="show-image">
          <strong>Host</strong>
          <%= link_to profile_path(@booking.room.user) do %>
            <%= cl_image_tag @booking.room.user.avatar.url(:profile_image), height: '100', width: '100', class: "profile-image" %>
          <% end %>
        </div>
        <div class="show-image">
          <strong>Musician</strong>
          <%= link_to profile_path(@booking.user) do %>
            <%= cl_image_tag @booking.user.avatar.url(:profile_image), height: '100', width: '100', class: "profile-image" %>
          <% end %>
        </div>
      </div>
      <div class="content">
        <p><strong>Host: </strong> <%= @booking.room.user.first_name + @booking.room.user.last_name %></p>
        <p><strong>Address: </strong> <%= @booking.room.address %></p>
        <p><strong>Start time: </strong> <%= @booking.start_time.strftime("%b %e, %l:%M %p") %></p>
        <p><strong>End time: </strong><%= @booking.end_time.strftime("%b %e, %l:%M %p") %></p>
        <p><strong>Total cost: </strong><%= @booking.room.currency %> <%= @booking.cost %> </p>
        <p><strong>Status: </strong><%= @booking.status.capitalize %></p>
      </div>
      <div class="links">
        <%= link_to booking_path(@booking),
            method: :delete,
            data: { confirm: "Are you sure you want to cancel this booking?" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
        <%= link_to bookings_path do %>
          <i class="fas fa-undo-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

app/views/pages/home.html.erb
<div class="home_search_wrapper">
  <div class="banner" style="background-image: linear-gradient(336deg, rgba(32,70,245,.8), rgba(32,70,245,0) 80.71%), url('https://images.unsplash.com/photo-1526142684086-7ebd69df27a5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f5767f515cad13d5aa42559ec8bb9a55&auto=format&fit=crop&w=1950&q=80');">
    <div class="banner-content">
      <h1 class="title">Be a Maestro</h1>
      <div class="home_form">
        <%= simple_form_for :room, url: rooms_path, wrapper: :inline_form, html: {class: 'form-inline'}, method: "get" do |f| %>
          <%= f.input :instrument_type, label: "Instrument", collection: ['Guitar', 'Cello', 'Piano', 'Drums', 'Harp'], prompt: "Find Instrument", input_html: {class: "dropbtn", style: 'width: 300px'} %>
          <%= f.input :location, collection: ['Shanghai', 'Seoul', 'Chengdu', 'Beijing', 'Hong Kong', 'Barcelona'], prompt: "Location", input_html: {class: "dropbtn", style: 'width: 300px'} %>
          <%= f.button :submit, "Go", class: "btn btn-primary home-button" %>
        <% end %>
      </div>
      <h2>Find the best space for your music</h2>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
 <div class="profile" style="background-image: linear-gradient(336deg, rgba(32,70,245,.8), rgba(32,70,245,.0) 70.71%)">
<div class="main-container" style="background-image: url('<%=image_path 'bg.png' %>');">
  <div class="results-container">
    <div class="dashboard-main-header">

      <h1>Find a Rehearsal Room</h1>

      <div class="map-form">
        <%= simple_form_for :room, url: rooms_path, wrapper: :inline_form, html: {class: 'form-inline'}, method: "get" do |f| %>
          <%= f.input :instrument_type, label: "Instrument", collection: ['Guitar', 'Cello', 'Piano', 'Drums', 'Harp', ''], selected: "#{params[:room][:instrument_type] unless params[:room].nil?}", prompt: "Instrument", input_html: {class: "dropbtn", style: 'width: 40%'} %>
          <%= f.input :location, collection: ['Shanghai', 'Seoul', 'Chengdu', 'Beijing', 'Hong Kong', 'Barcelona', ''], selected: "#{params[:room][:location] unless params[:room].nil?}", prompt: "Location", input_html: {class: "dropbtn", style: 'width: 40%'} %>
          <%= f.button :submit, "Filter", class: "btn map-btn", style: 'width: 18%' %>
        <% end %>
      </div>

    </div>

    <div class="row">

      <% @rooms.each do |room| %>
        <% if room.user != current_user %>
        <div class="col-xs-6">
          <%= link_to room_path(room) do %>
            <div class="card" id=<%= room.longitude %>>
              <% if room.room_images.count > 0 %>
                <div class="picture" style="background-image: url(<%= cl_image_path(room.room_images[0].image) %>);">
                </div>
              <% else %>
                <div class="picture" style="background-image: url('https://images.unsplash.com/photo-1526142684086-7ebd69df27a5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f5767f515cad13d5aa42559ec8bb9a55&auto=format&fit=crop&w=1950&q=80');">
                </div>
              <% end %>

              <div class="card-description">
                <h3><%= room.instrument_type %> in <%= room.location%></h3>
                <p>Host: <%= User.find(room.user_id).first_name %></p>
                <p>Location: <%= room.location %></p>
                <p>Rental price: <%= room.currency %> <%= room.price %>/hr</p>
              </div>
            </div>
          <% end %>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div
    id="map"
    style="width: 100%;
    height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>
<!-- </div> -->

app/views/rooms/myrooms.html.erb
<div class="profile" style="background-image: linear-gradient(145deg, rgba(45, 225, 207, 0.5), rgba(19, 123, 184, 0.6) )">
<div style="background-image:  linear-gradient(rgba(0,0,0,0.05), rgba(0,0,0,0.0)), url('<%=image_path 'bg.png' %>');">
<div class="dashboard myrooms">
  <div class="dashboard-main-header" >

    <% if @myrooms == [] %>
    <div id="myrooms-banner">
    <h1 id="myrooms-center">My Spaces</h1>
    <h3>🌟You don't have any rooms now...🌟</h3>
    <%= link_to "Create your first room", new_room_path, class: "btn btn-primary btn-home btn-myroom" %>
  </div>
  </div>
    <% else %>
    <h1>My Spaces</h1>

   <%= link_to "Add another room", new_room_path, class: "btn btn-primary btn-home btn-myroom" %>
   </div>
    <div class="row">
        <% @myrooms.each do |room| %>
          <div class="col-xs-6 col-xs-offset-3">
            <%= link_to room_path(room) do %>
              <div class="card">
                <% if room.room_images.count > 0 %>
                  <div class="picture" style="background-image:  url(<%= cl_image_path(room.room_images[0].image) %>);">
                  </div>
                <% else %>
                  <div class="picture" style="background-image:url('https://images.unsplash.com/photo-1526142684086-7ebd69df27a5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f5767f515cad13d5aa42559ec8bb9a55&auto=format&fit=crop&w=1950&q=80');">
                  </div>
                <% end %>

                <div class="card-description">
                  <h3><%= room.instrument_type %> in <%= room.location%></h3>
                  <p>Location: <%= room.location %></p>
                  <p>Rental price: <%= room.currency %><%= room.price %>/hr</p>
                </div>

                <div class="card-links">
                  <%= link_to "Edit", edit_room_path(room), class: "btn btn-card" %>
                  <%= link_to "Remove", room_path(room), class: "btn btn-card",
                    method: :delete,
                    data: { confirm: "Are you sure you want to delete?" } %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>

      </div>

  <% end %>
</div>
</div>
</div>

app/views/rooms/show.html.erb
<div class="whole-page-box">

  <div class="container room-container">
    <% if @room.room_images.count > 0 %>
      <div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path(@room.room_images[0].image) %>);">
      </div>
    <% else %>
      <div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1526142684086-7ebd69df27a5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f5767f515cad13d5aa42559ec8bb9a55&auto=format&fit=crop&w=1950&q=80');">
      </div>
    <% end %>
    <div class="show-box show-box-room">
      <div class="image-box">
        <div class="show-image">
          <%= link_to profile_path(@room.user) do %>
            <%= cl_image_tag @room.user.avatar.url(:profile_image), height: '100', width: '100', class: "profile-image" %>
          <% end %>
        </div>
      </div>

      <div class="title-box">
        <h1><%= @room.user.first_name %>'s <%= @room.instrument_type %> in <%= @room.location %></h1>
      </div>

      <div class="content">
        <p><strong>Host: </strong> <%= @room.user.first_name %> <%= @room.user.last_name %></p>
        <p><strong>Address: </strong> <%= @room.address %></p>
        <p><%= @room.description %></p>
        <p><strong>Price: </strong><%= @room.price %> <%= @room.currency %> per hour</p>
      </div>
      <div class="links">
        <% if @room.user == current_user %>
          <%= link_to edit_room_path(@room) do %>
            <i class="far fa-edit"></i>
          <% end %>
          <%= link_to room_path(@room),
            method: :delete,
            data: { confirm: "Are you sure you want to delete this room?" } do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
          <%= link_to bookings_path do %>
            <i class="fas fa-undo-alt"></i>
          <% end %>
        <% else %>
          <%= link_to "Book", new_room_booking_path(@room), class: "btn btn-home btn-myroom" %>
          <%= link_to rooms_path do %>
            <i class="fas fa-undo-alt"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

    <div
      id="map"
      style="width: 100%;
      height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Search", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Browse", rooms_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Hosting", my_rooms_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Dashboard", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.avatar.url != nil %>
            <%= cl_image_tag current_user.avatar.url(:navbar_image),  "data-toggle" => "dropdown" %>
          <% else %>
            <%= link_to '', "data-toggle" => "dropdown" do %>
              <i class="fas fa-user" style='color: #0000b3' ></i>
            <% end %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profile_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Create account", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Login", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
</div>